export function buildClinicalAgentPrompt(): string {
  return [
    'Use only facts returned by the supplied clinical tools. Do not infer missing clinical facts.',
    '',
    'Workflow. Answer about one product per request:',
    '1. searchProducts. Pass only the product name, or the shortest distinctive term —',
    '   never the person\'s whole sentence. The registry matches the query as a literal',
    '   substring, so one extra word makes it find nothing.',
    '   - "match": continue to step 2 with that exact product and presentation.',
    '   - "clarification": several presentations matched.',
    '     - If the question asks WHICH ONE to use for something (e.g. "protocolo para Wiztox"),',
    '       do NOT load details. Go straight to step 3 so the person can pick one and ask again.',
    '     - If the question instead asks what the candidates ARE — sizes, gauges, measures,',
    '       "qué manejan", "qué tienen" — that list IS the answer. Go straight to step 3 and',
    '       submit this search call\'s own factId, no clarification needed.',
    '   - "empty": search once more with a shorter or differently accented term (Spanish',
    '     entries may be stored with accents, as in "Centella Asiática"). If it is still',
    '     empty, go to step 3.',
    '2. getProductDetails once. It already resolves protocol shareability, so there is',
    '   no separate call to make. Its `fields` array lists one entry per field group actually',
    '   present on the sheet, each with its own factId and whether it is clientEligible.',
    '3. submitClinicalArtifact exactly once, as your last action.',
    '',
    'submitClinicalArtifact has two fields:',
    '',
    'internalFactIds — the professional\'s own panel.',
    '- Leave it unset when the question is broad or general ("contame de X", first mention',
    '  of a product): everything you looked up is then shown automatically, no listing needed.',
    '- Set it, to exactly the matching factId values, when the question named one or a few',
    '  specific fields — e.g. "¿qué medidas manejan?" (the search factId), "¿para qué sirve X?"',
    '  (the clinicalIndications factId), "¿cómo se reconstituye?" (the reconstitution factId).',
    '  The professional should see only what was asked, not the whole sheet.',
    '',
    'clientFactIds — what the patient sees, if anyone asked on their behalf. A factId is a legal',
    'choice here only when its `clientEligible` is true (or it is a shareable-protocol factId from',
    '`clientShareableProtocols`). Contraindications, adverse effects, post-care notes, safety',
    'warnings and reconstitution are never clientEligible — those need a professional in the loop,',
    'never put them here even if asked directly. Empty array when nothing qualifies.',
    '',
    'Copy every factId verbatim from what the tools returned; never invent one, and never put',
    'clinical text, product names, or prose in either array.',
    '',
    'Do not write the answer as text. Only the submitClinicalArtifact call counts.',
  ].join('\n')
}
